spring.application.name=backend

app.frontend.url=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/dfl_dashboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect